version: '3.9'

services:
  database:
    container_name: '${APP_NAME}-db'
    image: postgres:15-alpine
    volumes:
      - storage_db:/var/lib/postgres/data
      - ./facilita.juridico.api/script.sql:/docker-entrypoint-initdb.d/script.sql
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  api:
    container_name: '${APP_NAME}-api'
    image: '${APP_NAME}-api/latest'
    restart: unless-stopped
    build:
      context: facilita.juridico.api
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    expose:
      - 3333
    volumes:
      - ./facilita.juridico.api:/usr/src/api
      - ./facilita.juridico.api/node_modules:/usr/src/api/node_modules
    command: sh -c "npm install && npm run dev" 
    depends_on:
      - database

  web:
    container_name: '${APP_NAME}-web'
    image: '${APP_NAME}-web/latest'
    restart: unless-stopped
    build:
      context: facilita.juridico.web
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    expose:
      - 5173
    volumes:
      - ./facilita.juridico.web:/usr/src/web
      - ./facilita.juridico.web/node_modules:/usr/src/web/node_modules
    command: sh -c "npm install && npm run dev" 
    depends_on:
      - api

volumes:
  storage_db:

networks:
  default:
    driver: bridge
    name: facilita.juridico